song_lyrics = "I find it hard to say the things I want to say the most\nFind a little bit of steady as I get close\nFind a balance in the middle of the chaos\nSend me low, send me high, send me never demigod\nI remember walking in the cold of November\nHoping that I make it to the end of December\n27 years and the end on my mind\nBut holding to the thought of another time\nBut looking to the ways of the ones before me\nLooking for the path of the young and lonely\nI don't want to hear about what to do\nI don't want to do it just to do it for you\n \nHello, hello\nLet me tell you what it's like to be a zero, zero\nLet me show you what it's like to always feel, feel\nLike I'm empty and there's nothing really real, real\nI'm looking for a way out\n \nHello, hello\nLet me tell you what it's like to be a zero, zero\nLet me show you what it's like to never feel, feel\nLike I'm good enough for anything that's real, real\nI'm looking for a way out\n \nI find it hard to tell you how I want to run away\nI understand it always makes you feel a certain way\nI find a balance in the middle of the chaos\nSend me up, send me down\nSend me never demigod\n \nI remember walking in the heat of the summer\nWide eyed one with a mind full of wonder\n27 years and I've nothing to show\nFalling from the dove to the dark of the crow\nLooking to the ways of the ones before me\nLooking for a path of the young and lonely\nI don't want to hear about what to do, no\nI don't want to do it just to do it for you\n \nHello, hello\nLet me tell you what it's like to be a zero, zero\nLet me show you what it's like to always feel, feel\nLike I'm empty and there's nothing really real, real\nI'm looking for a way out\n \nHello, hello\nLet me tell you what it's like to be a zero, zero\nLet me show you what it's like to never feel, feel\nLike I'm good enough for anything that's real, real\nI'm looking for a way out\n \nLet me tell you bout it\nLet me tell you bout it\nMaybe you're the same as me\n \nLet me tell you bout it\nLet me tell you bout it\nThey say the truth will set you free\n \nHello, hello\nLet me tell you what it's like to be a zero, zero\nLet me show you what it's like to always feel, feel\nLike I'm empty and there's nothing really real, real\nI'm looking for a way out\n \nHello, hello\nLet me tell you what it's like to be a zero, zero\nLet me show you what it's like to never feel, feel\nLike I'm good enough for anything that's real, real\nI'm looking for a way out"

def find_K(song):
    count = 0
    for letter in song:
        if letter == 'k':
            count += 1
        elif letter == 'K':
            count += 1
    return count

print(find_K(song_lyrics))